### ISSUE TITLE
5120x2160 resolution at 150% UI size not working as expected

### ISSUE THREAD

**Issue by divStar** [SteffenL/doa5lr-resolution-mod#1]
Hello there,

first of all: thank you for such a great tool! I am finally able to play the game in a brilliant 5k2k resolution (MSI Prestige PS341WU display).

I am experiencing a problem though. If I am not at 100% zoom (display settings in Windows 10), the window created is too big - most certainly more than 5120x2160.  So if I am at 150% zoom (which I usually use), the window is of (5120 * 1.5) Pixels in width. For whatever reason the height seems to be correct, I think.

If you have a fix, I'd gladly test it. I am using a laptop (i7-10510U), 16GB RAM, SSD and a 1080GTX eGPU and it seems the latter is barely making it (while being able to run Rocket League at max settings). I am not sure what is causing this since I am not using ReShade or the likes.

Edit: I found out more: if you use the compatibility mode, you can try to ensure the DPI for the application is changed to 100% (whatever default display DPI you have). Setting this in the properties -> compatibility -> change HiDPI settings -> both checkboxes and varying combobox-values works for me.

But I'd of course much rather not rely on Windows being as smart as this. So if it is possible to fix the application somehow, it'd be great. I am also trying to figure out the source of stuttering (the game often plays well in 5120x2160, but sometimes starts to stutter), but I guess there's something else nagging on the performance.

**Comment by SteffenL** [comment]
Hello and thanks for the feedback!

Which version are you using of the resolution mod? Have you tried 0.4.0 available here on GitHub?

I am not sure what could cause stuttering but 0.4.0 has some improvements that could help. There were known issues when using other mods like ReShade but this should be fixed along with new documentation for using e.g. ReShade with better performance.

Does the stuttering occur with the game's officially supported resolutions as well, and does it occur only when using my mod? How about lower resolutions?

Does the game create a window larger than expected with 150% scaling when my mod is not installed?

I'm glad you found a workaround! Well done! It would certainly be helpful if people didn't have to fiddle with such things so I'll try to see if I can do something about it.

**Comment by divStar** [comment]
Hello Steffen,

I am using version 0.4.0 (from GitHub). As mentioned I am not using ReShade (I did give it a try on my previous computer, but was not that impressed, so I left it out this time).

Weirdly enough the stuttering indeed does happen without your modification - which is perplexing me, because I had no idea this would happen. I will be investigating this further. The Windows resource monitor keeps throwing "hard errors" at me, possibly hinting that the RAM I have in my laptop might be damaged... but this shouldn't be the case... I think...

The stuttering indeed happens when these "hard errors" seem to occur - I have no idea why they occur in the first place and to be honest I don't remember having any stuttering just a few days ago, but then again I did adjust various configurations - so who knows what's really going on.

By default (and with my default DPI) the mod_resolution 0.4.0 create a window of around 7680 x 2160 (I have a 5120 x 2160 main monitor and my laptop screen used to be on). However: I think the reason behind this is the 150% scaling. When I switched to 100% scaling, the window resolution was almost perfectly (I still do see part of the task bar).

I shall report back on my findings regarding DPI and stuttering. Thank you for your reply and such a great tool :)!

**Comment by SteffenL** [comment]
The mod uses the game's own window creation routines so this is what you get with the game out of the box, but I was able to find an easy fix for this.

0.5.0 has been released with a new option for enabling DPI awareness to prevent the game window from scaling along with the scaling setting in Windows.

I've tested up to 3840x2160 resolution with 200% scaling.

To use the new option you need to add `DpiAware=1` under `[Video]` in `mod_resolution.ini`. If you delete `mod_resolution.ini` then the installer will do that for you.

**Comment by divStar** [comment]
Hi there!

First of all: thank you very much for your work!

Sadly 0.5.0 does not resolve the DPI issue - which is strange.

I have replaced the files and configured the mod_resolution.ini as follows:
```
; Configuration file for DO5LR Resolution Mod.
; Created by Steffen André langnes.
; https://www.steffenl.com

[Video]
; Set any resolution you want, e.g. 2560x1440 or 3440x1440, or leave empty to disable.
Resolution=5120x2160
; Fix the image aspect ratio based on the specified resolution.
; Set this 1 (enable) or 0 (disable).
FixAspectRatio=1
; Enables DPI awareness causing the game window to not scale along with the scaling setting in Windows.
; Set this 1 (enable) or 0 (disable).
DpiAware=1
; Stretches the image to the full width, removing black bars for wide resolutions.
; Set this 1 (enable) or 0 (disable).
FixViewport=1

; DLL calls can be forwarded to other DLLs by specifying them here.
; This allows co-existence with mods that provide their own proxy libraries (e.g. d3d9.dll).
;
; ReShade:
;   1. Move ReShade's d3d9.dll file to reshade\d3d9.dll and specify "d3d9=reshade\d3d9.dll" below.
;   2. In the ReShade.ini file, change ".\" to "..\".
[Proxy]
; Direct3D 9 (d3d9.dll)
d3d9=

[Log]
; Log level for filtering log messages.
; Should be set to at least 1 (error) to get error messages.
; Set to 3 (debug) when troubleshooting.
; 0 = silent; 1 = error; 2 = info; 3 = debug
Level=2
; The path to the log file.
File=mod_resolution.log
```
The scaling settings for my first monitor (the WUHD one is the primary monitor) are as follows:
![grafik](https://user-images.githubusercontent.com/138585/86798064-ad9f7480-c070-11ea-858f-31f22afaf25e.png)
![grafik](https://user-images.githubusercontent.com/138585/86797268-c52a2d80-c06f-11ea-990a-3883d4f81f64.png)

But what I get in the end is this:
![grafik](https://user-images.githubusercontent.com/138585/86797685-4255a280-c070-11ea-9499-0a7dabe11a20.png)

The fact that the window does not start at 0, 0 is not a problem - I can easily use ALT+Space and move the window down using the cursor. The problem of the DPI/scale still persists though.

Is there perhaps anything else I have to do to make the game scale-aware? Reducing those 150% to 100% still fixes the issue.

Just in case you are wondering if I have the correct d3d9.dll:
![grafik](https://user-images.githubusercontent.com/138585/86798314-ec352f00-c070-11ea-842d-69ffdaa904d7.png)

**Comment by SteffenL** [comment]
In the configuration, can you please set `Level=3` under `[Log]`, run/close the game and then share the contents of `mod_resolution.log`?

**Comment by SteffenL** [comment]
I have only tested this with a single monitor but it looks to me like you are using multiple monitors.

Just for clarification, are you expecting the game window to stretch across multiple monitors?

**Comment by divStar** [comment]
No, @SteffenL , I am not expecting the game to stretch over several monitors. I'd like it to be displayed on one monitor only - the WUHD display. And it does so flawlessly if I switch to 100% scaling and then start the game.

**Comment by divStar** [comment]
I just tested both with the second screen off and on and it works as expected. I didn't change any files, but perhaps something was "cached" somehow? Because in-between reporting the error and trying it now I rebooted. So perhaps a reboot was necessary for some reason?

Anyhow - now it works both with the second screen staying on and enhancing the first (bigger) screen and with it off. In both cases and on 150% scale the window is placed almost as expected (there is a tiny piece of the taskbar visible, but I assume if I hid the taskbar it would be perfect).

Thank you!

By the way - in regards to the stuttering: I - assume - it might somehow relate to the external GPU not getting enough watts from the plug. It worked quite well just now (there was some minor stuttering, but barely noticeable).

I also got Dead or Alive 6 yesterday and wondered if you played it, too. While it has now native resolution adjustments, it - once again - does not support anything as fancy as 21:9. One has to unpack and edit the executable file in order to get that resolution (I tried it, but got the resolution wrong) and while there are ready-made executables for older version, there is none for the current version 1.22a (#8 I believe).

Anyhow - thank you very much for your help! The game is a joy on the display. Do you have paypal or something where I can send you some coins for a beer or two?

**Comment by SteffenL** [comment]
To my surprise while testing this again, I found the same weird behavior. It's like you said, something appeared "cached". Then it somehow worked properly again. I will try to reproduce it and then see if there is a way to invalidate the cache if that is what it is.

Are you running the game windowed at full resolution? Just curious because the game originally has a title bar and border which could perhaps be a bit annoying.

I hope you get that stuttering sorted out somehow!

I have not played DOA6 yet although I did install it a few days ago. I also haven't really looked into whether there is any demand for this kind of mod for DOA6.

I am happy and appreciate your wish to support me! It really helps! I've just now added a "Support R&D" button on my website for those who whish to donate: https://www.steffenl.com/

**Comment by divStar** [comment]
Somehow after re-attaching the eGPU the stuttering is mostly gone, though I still don't entirely understand how it comes to be.

I am playing DOA5 with the mod at full resolution (5120x2160) in windowed mode (I can't turn it into full-screen, right?). Now that you mention the title bar - it might just as well be part of that title bar. No idea.

In my opinion this issue is resolved (even though that "caching"-stuff is weird somehow, but nevertheless it does work now properly except after changing from 100% to 150% and not rebooting (or perhaps re-logging is enough?)). If you happen to figure out the "caching"-issue, that'd be awesome, but nevertheless it works now :).

Oh and in regards to DOA6: it is already currently possible, but one has to modify the actual executable and then the resolution is fixed and unmodifiable. I am sure if there was a way to do it in a more user-friendly manner, it'd be a nice mod for all those, whose aspect ratios are not supported.
After the modification (in DOA6) the menus are not stretched and one won't see a difference until a match actually starts.

Anyhow: thank you! And I've used that button :). If you ever happen to be in southern Germany, let me know - I'll definitely invite you for a drink or something. Cheers!

**Comment by SteffenL** [comment]
That was a generous donation! Thank you very much! :D

My mod supports using the full resolution with fullscreen through the game's own window creation. If you haven't already then I suggest trying to go into the game's own config and change it to fullscreen.

Thanks for explaining regarding DOA6! Maybe I can take a look at it and see what I can do. :)

If there is a way to reproduce the "caching" stuff then I think it will be a good candidate for a new issue.

**Comment by SteffenL** [comment]
I found that once I run the game through Steam with `DpiAware=0` then the game can be launched with DPI awareness enabled. If I then try to run the game's executable directly (`game.exe`) then it launches without DPI awareness. Launching it again with Steam makes it DPI aware somehow. Restarting Steam and then the game via Steam caused the game to lose the DPI awareness.

**Comment by SteffenL** [comment]
I believe I have fixed (6904d02c81ea4f45d00ccb1a089fee4bdf7672ce) the DPI awareness "caching" by using newer API for setting the DPI awareness depending on the version of Windows:

* [`SetThreadDpiAwarenessContext`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setthreaddpiawarenesscontext) is used for Windows 10 and restores the previous DPI awareness on shutdown.
* [`SetProcessDpiAwareness`](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness) for Windows 8.1 and restores the previous DPI awareness on shutdown.
* [`SetProcessDPIAware`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware) otherwise (Windows 8 and earlier) which cannot be turned off.

I just need to test this on Windows 8.1 and Windows 7 to make sure it does not crash due to missing API.

**Comment by SteffenL** [comment]
Fixed in version 0.5.1 (see 3e9510b18ac4d66f9a6dfad335d3c5882a0d3b05) by using newer DPI awareness API where available. Let me know if you have any more troubles. :)

**Comment by SteffenL** [comment]
FYI, I created a repository for DOA6: https://github.com/SteffenL/doa6-resolution-mod
